# Generated by Django 5.2 on 2025-06-08 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('area_type', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], max_length=10)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lump_sump', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_bigha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('male_labors', models.PositiveIntegerField(blank=True, null=True)),
                ('female_labors', models.PositiveIntegerField(blank=True, null=True)),
                ('is_accepted_by_farmer', models.BooleanField(default=False)),
                ('is_accepted_by_labor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bid',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('labor', 'Labor'), ('tractor', 'Tractor')], default='labor', max_length=10)),
                ('hourly', models.BooleanField(default=False)),
                ('lump_sump', models.BooleanField(default=False)),
                ('per_bigha', models.BooleanField(default=False)),
                ('per_day', models.BooleanField(default=False)),
                ('per_weight', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'village',
            },
        ),
        migrations.CreateModel(
            name='BidComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bid')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bid_comment',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('areas', models.ManyToManyField(blank=True, to='api.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('villages', models.ManyToManyField(to='api.village')),
            ],
            options={
                'db_table': 'farmer',
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.village')),
            ],
            options={
                'db_table': 'labor',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='labor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.labor'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('shift', models.CharField(choices=[('anytime', 'Any Time'), ('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night'), ('fullday', 'Full Day')], max_length=10)),
                ('number_of_labors', models.PositiveIntegerField(blank=True, null=True)),
                ('has_pickup', models.BooleanField(default=False)),
                ('snacks_facility', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('farmer_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farmer')),
                ('hire_labor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.labor')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
            ],
            options={
                'db_table': 'requirement',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requirement'),
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('villages', models.ManyToManyField(to='api.village')),
            ],
            options={
                'db_table': 'tractor',
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='hire_tractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tractor'),
        ),
        migrations.AddField(
            model_name='bid',
            name='tractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tractor'),
        ),
        migrations.AddField(
            model_name='area',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.village'),
        ),
        migrations.CreateModel(
            name='TractorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(limit_choices_to={'skill_type': 'tractor'}, on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tractor')),
            ],
            options={
                'db_table': 'tractor_skill',
                'unique_together': {('tractor', 'skill')},
            },
        ),
    ]
